### ISSUE TITLE
ActionFilter does not handle value-type Result values

### ISSUE THREAD

**Issue by gplwhite** [ElysiumLabs/FluentResults.Extensions.AspNetCore#1]
I noticed that the ActionFilter requires the result to implement `IResult<object>`. 

This means the filter does not correctly deal with Results that encapsulate value types (eg: int or enum). It also doesn't deal with Results that don't have a value (eg: Result.Ok()).

In these cases the filter does not touch the action result - meaning the Result object is passed through and serialised to the response output, when either a ProblemDetails instance or the encapsulated value is expected.

**Comment by angusbreno** [comment]
Thanks! This feature is really important. 
I will be generating the package later today.

**Comment by angusbreno** [comment]
https://github.com/ElysiumLabs/FluentProblemDetails/discussions/4

Greg for when you can.
